### ISSUE TITLE
npe_diversity_info error with vegan::diversity

### ISSUE THREAD

**Issue by mrunj** [admahood/neonPlantEcology#9]
running npe_diversity_info produces the following error:
> di <- npe_diversity_info(all_sites)
Error in `dplyr::mutate()`:
ℹ In argument: `shannon_exotic = vegan::diversity(...)`.
Caused by error in `vegan::diversity()`:
! input data must be non-negative
Run `rlang::last_trace()` to see where the error occurred.

I believe the issue comes from the line:
 vegan::diversity(vegan_friendly_div_ex %>%
 dplyr::select(-site, -plotID, -subplotID, -eventID))
which is either receiving negative values or is maybe just unhappy with the syntax of using "-" in  dplyr::select

**Comment by mrunj** [comment]
did a little more digging and the vignette doesn't produce the error because the analysis only includes data from a single domain. If npe_download_plant_div pulls data for multiple domains then the produced object produces the error when passed to npe_diversity_info. But even then it only produces errors when timescale="annual" which is the default for the function, but is not the value used in the vignette

**Comment by mrunj** [comment]
Kept digging, I now don't think it is a problem with there being multiple sites anymore. It looks like it is actually an issue with the underlying data. If there is an NA in the original percent cover data, when you summarise it (I think at the plot level, the na.rm argument isn't working right and is producing a -Inf value, which is in turn causing an issue (because of the negative value) when calculating diversity metrics.

**Comment by admahood** [comment]
This should work now with neonPlantEcology version 1.1.2
